<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Chat;
use AppBundle\Entity\User;

/**
 * ChatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param array $message
     *
     * @return Chat
     */
    public function saveMessage(User $user, array $message)
    {
        $chatMessage = new Chat();
        $chatMessage
            ->setMessage($message['message'])
            ->setType($message['type'])
            ->setUser($user)
            ->setCreated($message['postTime']);

        $this->_em->persist($chatMessage);
        $this->_em->flush($chatMessage);

        return $chatMessage;
    }
}
