<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Match;
use AppBundle\Entity\User;

/**
 * MatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Match $match
     *
     * @return bool
     */
    public function save(Match $match)
    {
        $this->_em->persist($match);
        $this->_em->flush($match);

        return true;
    }

    /**
     * @param User $user
     *
     * @return null|object
     */
    public function getActiveMatchByUser(User $user)
    {
        return $this->findOneBy(
            [
                'player' => $user->getId(),
                'active' => true,
            ]
        );
    }

    /**
     * @param User $user
     *
     * @return Match|null
     */
    public function getOpponentInfo(User $user)
    {
        /** @var Match $match */
        $match = $this->findOneBy(
            [
                'player' => $user->getId(),
                'active' => true,
            ]
        );

        $query = $this->createQueryBuilder('m')
            ->where('m.code = :matchCode AND m.player != :playerId')
            ->setParameters(
                [
                    'matchCode' => $match->getCode(),
                    'playerId'  => $user->getId(),
                ]
            )
            ->getQuery();

        return $query->setMaxResults(1)->getOneOrNullResult();
    }

}
