<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Rating;
use AppBundle\Entity\User;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param User $userId
     *
     * @return null|object
     */
    public function getRatingByUser(User $user)
    {
        return $this->findOneBy(['user' => $user]);
    }

    /**
     * @param Rating $rating
     *
     * @return bool
     */
    public function save(Rating $rating)
    {
        $this->_em->persist($rating);
        $this->_em->flush($rating);

        return true;
    }
}
