<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use AppBundle\Entity\UserStatus;

/**
 * UserStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStatusRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param User $user
     * @param int $status
     *
     * @return UserStatus
     */
    public function changeStatus(User $user, int $status)
    {
        $userStatus = $user->getStatus();
        $userStatus
            ->setStatus($status)
            ->setLastChangeTime(new \DateTime());

        return $this->save($userStatus);
    }

    /**
     * @param UserStatus $userStatus
     *
     * @return UserStatus
     */
    public function save(UserStatus $userStatus)
    {
        $this->_em->persist($userStatus);
        $this->_em->flush($userStatus);

        return $userStatus;
    }
}
