<?php

namespace AppBundle\Repository;

use AppBundle\DTO\Proxy\UserInfoResponse;
use AppBundle\Entity\User;
use AppBundle\Entity\UserStatus;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param UserInfoResponse $userInfo
     *
     * @return User
     */
    public function createUser(UserInfoResponse $userInfo)
    {
        $user = new User();
        $user
            ->setName(!is_null($userInfo->name) ? $userInfo->name : 'test')
            ->setLogin($userInfo->sub)
            ->setRole(User::PLAYER_USER_ROLE)
            ->setRobotModel(1)
            ->setRobotColor('000')
            ->setVip(false)
            ->setPoints(0)
            ->setCurrentPoints(0)
            ->setWins(0)
            ->setLoses(0)
            ->setLastFightTime(new \DateTime('yesterday'))
            ->setMaxFightWaitingTime(0);

        $userStatus = new UserStatus();
        $userStatus
            ->setUser($user)
            ->setStatus(UserStatus::RESTING)
            ->setLastChangeTime(new \DateTime());

        $this->_em->persist($user);
        $this->_em->persist($userStatus);
        $this->_em->flush();

        return $user;
    }

    /**
     * @param User $user
     *
     * @return User
     */
    public function save(User $user)
    {
        $this->_em->persist($user);
        $this->_em->flush();

        return $user;
    }
}
